# Generated by Django 5.0.2 on 2024-02-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('state', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('location', models.TextField(blank=True, null=True)),
                ('image_cloudinary_url', models.URLField(blank=True)),
                ('resume_cloudinary_url', models.URLField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
